### ISSUE TITLE
Injector sometimes not working

### ISSUE THREAD

**Issue by opoisso893** [Red-J/PS4-Avatar-dumper-writer-4.55-5.05#1]
No error while using Injector but avatars are not injected.
Using FTP for same avatar is working well.
Is it possible to have a log file on USB when using injector to check any issue during the copy process?

**Comment by Red-J** [comment]
you must verify your folder name and if you are on usb0 log can be created

**Comment by opoisso893** [comment]
Made new test this morning and it works for all my accounts except one. Maybe something wrong on my PS4 5.05 with all my tests ;)
I close this issue.
